### ISSUE TITLE
Add Quixote

### ISSUE THREAD

**Issue by jamesshore** [thingsinjars/csstest#10]
Quixote is a forthcoming tool in the "Computed Style" category.

GitHub: https://github.com/jamesshore/quixote

Announcement: http://www.letscodejavascript.com/v3/blog/2014/09/announcing_quixote

**Comment by paulirish** [comment]
just as some feedback, i think you should give extra thought to what sort of assertions you want to have. 

should be cool. goodluck!

**Comment by jamesshore** [comment]
I've opened https://github.com/jamesshore/quixote/issues/1 for discussing assertion design ideas.

**Comment by thingsinjars** [comment]
Added to the tools section. I like the idea of generating the values relative to other elements so I'll need to play with it a bit.

**Comment by jamesshore** [comment]
Thanks. Should it be added to the "Computed Style" page? http://csste.st/techniques/computed-style.html

**Comment by thingsinjars** [comment]
Oops. Good catch. I think I need to automate a few more bits of the site generation. I also added you to the new [videos section](http://csste.st/guides/videos/).
