### ISSUE TITLE
add tools from the slides

### ISSUE THREAD

**Issue by paulirish** [thingsinjars/csstest#2]
http://csste.st/slides/

also
http://www.peterbe.com/plog/mincss

**Comment by thingsinjars** [comment]
Shazam! All the tools from the slides now have entries (67cf8f4), some more detailed than others. Also added a really basic summary of MinCSS and Fighting Layout Bugs, both of which require a bit more write-up once I've played with them more.

Thanks for the nudge, the ramp-up after Christmas is slooow...

**Comment by paulirish** [comment]
http://csste.st/tools/  ! lookin sharp
nice
