### ISSUE TITLE
[csstest] Page build failure

### ISSUE THREAD

**Issue by pablopaul** [thingsinjars/csstest#6]
I got 2 E-Mails for my commits:

The page build failed with the following error:  
CNAME already taken: csste.st  

For information on troubleshooting Jekyll see https://help.github.com/articles/using-jekyll-with-pages#troubleshooting If you have any questions please contact GitHub Support.  support@github.com https://github.com/contact

What is that about?

**Comment by thingsinjars** [comment]
Darn. I always wondered how CNAMEs worked with forks. Apparently they don't. I guess just ignore the warning for just now and I'll ask someone who knows more than me.

**Comment by thingsinjars** [comment]
Okay, it seems that the recommended thing to do is remove the CNAME from your fork but make sure not to include it in pull requests. That seems odd but it looks like a bit of a limitation of the extremely clever subdomain system of GitHub.

**Comment by pablopaul** [comment]
@thingsinjars Thanks for the investigation, but i don´t think the problem is really solved for me, because i can´t find a proper solution to ignore the "CNAME" file locally/in my fork while not including it into a future pull request against the csstest head repository. At the pull request creation level in GitHub UI i can´t exclude a specific commit. Probably i could not push the commit from my local repository to my fork on GitHub, but that would be something where everybody has to pay attention on every push – feels not very handy for the future …

Another idea was to exclude/ignore the "CNAME" file from the repository at all and let the build system take care of its creation, what do you think? It seems also not like a perfect solution because the information about the existence of the "CNAME" file would live in the build script, not directly in the repository… mhm …

**Comment by thingsinjars** [comment]
That's not a bad idea. I think I'll do something similar: move the `CNAME` to `_CNAME` in the repo then `mv` during build. Keeps the file in the project, not the build system; prevents the duplicate record error. I think.

**Comment by pablopaul** [comment]
Sounds good!
Another option for contributors could be: Create a branch which is not called "gh-pages" for the desired changes. My guess is that GitHub only uses the "CNAME" file in a branch with the specific name… I tested it with a test-branch and i did not get any build error. 

Its up to you, for me both ways are alright.
